[workspace]
resolver = "2"
members = [
    "src/bk2-format",
    "src/cyclone-v",
    "src/de10-nano",
    "src/fce-movie-format",
    "src/golem",
    "src/golem-core",
    "src/golem-script",
    "src/golem-ui",
    "src/mister-fpga",
    "src/nfc-tester",
    "src/taser",
]

[profile.release]
lto = true
overflow-checks = false
panic = "abort"
#strip = true
#debug = false

[profile.dev]
overflow-checks = false
debug = 0
panic = "abort"

[workspace.dependencies]
image = "0.25"

# Repo crates
bk2-format = { path = "src/bk2-format" }
cyclone-v = { path = "src/cyclone-v" }
de10-nano = { path = "src/de10-nano" }
fce-movie-format = { path = "src/fce-movie-format" }
golem = { path = "src/golem" }
one-fpga = { path = "src/golem-core", version = "0.1.0" }
golem-script = { path = "src/golem-script" }
golem-ui = { path = "src/golem-ui" }
junior = { path = "src/junior" }
mister-fpga = { path = "src/mister-fpga" }
senior = { path = "src/senior" }
taser = { path = "src/taser" }
